Add files via upload
animals sort is almost somewhat successful in one scanario. soon it will be good!!!

diff --git a/animalsort b/animalsort
--- a/animalsort
+++ b/animalsort
@@ -1,9 +1,11 @@
 #!/bin/bash
 
 #this will work currently for paste, but if you change it to adiffrent order (like red blue orange green) it messes it up
-color=(green blue orange red)
+color=(blue green orange red)
 
 srtsys () {
+#im pretty sure i went wrong somewhere here? im suppose to use 
+# value=$@ but it works anyway
 value=$1
 for i in ${value[@]}; do
 	cat $a $b $c | grep $i | cat > i
@@ -12,6 +14,39 @@ done
 return
 }
 
+srtslct(){
+value=$@
+num=0
+for i in ${value[@]}; do
+	echo " $num . $i"
+	num=$(($num + 1))
+done
+
+return
+
+}
+#insert simple menu here
+simplemenudec () {
+value=$@
+if [[ $REPLY =~ ^[0-3]$ ]]; then
+	if [[ $REPLY == 1 ]]; then
+		echo "fart fart fart"
+		exit
+	fi
+	if [[ $REPLY == 2 ]]; then
+		echo $(date)
+		exit
+	fi
+	if [[ $REPLY == 3 ]]; then
+		echo "butt butt butt"
+		exit
+	fi
+else
+	echo "invalid, cant you read?" >&2
+	exit 1
+fi
+return
+}
 echo "animalsort is here to try and sort animals and things into diffrenct catagories currently designed for 3 files at once
 
 "
@@ -39,7 +74,15 @@ if [[ $REPLY =~ ^[1-2]$ ]]; then
 	if [[ $REPLY == 1 ]]; then
 		srtsys "${color[@]}"
 		#my current understanding of past in it's relation to forming columns is poor. It's very possible that i will change it, change it to a non txt file format and fuck it all up :(
-		paste "${color[@]}"
+		#woo i did it!!
+		paste "${color[@]}" | expand -t 30
+		echo ${color[@]}
+		
+		srtslct "${color[@]}"
+		echo -n "which of the following selection would you like? 0-$((${#color[@]}-1))
+		"
+		read REPLY
+
 		exit
 	fi
 	if [[ $REPLY == 2 ]]; then
